import {useEffect,useState} from 'react';
import {AnimatePresence,motion} from 'framer-motion';
import {ArrowLeft,ArrowRight,Leaf,Sprout,CloudSun,ShieldCheck,X,Pause,Play,Mic,BarChart3} from 'lucide-react';
import {translate as tr} from '../lib/i18n';
const icons=[Leaf,Sprout,CloudSun,ShieldCheck];
const art=['field','readings','weather','decisions'];
export default function Tutorial({open,onClose,onFinish,language}){
 const [step,setStep]=useState(0),[playing,setPlaying]=useState(false); const steps=[['step1Title','step1Text'],['step2Title','step2Text'],['step3Title','step3Text'],['step4Title','step4Text']];
 useEffect(()=>{if(open){setStep(0);setPlaying(false)}},[open]);
 useEffect(()=>{if(!open||!playing)return;const id=setInterval(()=>setStep(s=>{if(s>=steps.length-1){setPlaying(false);return s}return s+1}),5000);return()=>clearInterval(id)},[open,playing]);
 useEffect(()=>{if(!open)return;const key=e=>{if(e.key==='ArrowRight')setStep(s=>Math.min(s+1,steps.length-1));if(e.key==='ArrowLeft')setStep(s=>Math.max(s-1,0));if(e.key==='Escape')onClose()};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[open,onClose]);
 if(!open)return null; const Icon=icons[step];const [title,text]=steps[step]; const finish=()=>{localStorage.setItem('climate-tutorial-done','1');onFinish?.();onClose()}; const skip=()=>{localStorage.setItem('climate-tutorial-done','1');onClose()};
 return <AnimatePresence><motion.div className="tutorial-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div className="tutorial-card" initial={{y:28,opacity:0,scale:.96}} animate={{y:0,opacity:1,scale:1}} exit={{y:18,opacity:0}} role="dialog" aria-modal="true"><button className="icon-btn tutorial-close" onClick={skip} aria-label={tr(language,'close')}><X/></button>
  <div className={'tutorial-visual tutorial-'+art[step]}><div className="tutorial-field-art"><span className="tutorial-sun"/><span className="tutorial-hill h1"/><span className="tutorial-hill h2"/><span className="tutorial-barn"/><span className="tutorial-crop-lines"/></div><div className="tutorial-orbit"><Icon/></div><div className="tutorial-progress"><span style={{width:`${((step+1)/steps.length)*100}%`}}/></div><div className="tutorial-dots">{steps.map((_,i)=><button aria-label={`${tr(language,'step')} ${i+1}`} onClick={()=>{setStep(i);setPlaying(false)}} className={i===step?'active':''} key={i}/>)}</div></div>
  <div className="tutorial-copy"><span className="eyebrow">FIELD GUIDE · {step+1}/4</span><h2>{tr(language,title)}</h2><p>{tr(language,text)}</p><div className="tutorial-example"><span>{tr(language,'guideTip')}</span><b>{step===0?'Farm + crop':step===1?'Temperature + moisture':step===2?'AI + weather context':'Risks + actions + harvest'}</b></div><div className="tutorial-auto"><span>{playing?tr(language,'autoPlaying'):tr(language,'manualGuide')}</span><button className="secondary small" onClick={()=>setPlaying(v=>!v)}>{playing?<><Pause size={14}/>{tr(language,'pause')}</>:<><Play size={14}/>{tr(language,'play')}</>}</button></div><div className="tutorial-actions"><button className="ghost" onClick={skip}>{tr(language,'skip')}</button><div className="tutorial-nav">{step>0&&<button className="secondary" onClick={()=>{setStep(s=>s-1);setPlaying(false)}}><ArrowLeft size={16}/>{tr(language,'back')}</button>}{step<steps.length-1?<button className="primary" onClick={()=>{setStep(s=>s+1);setPlaying(false)}}>{tr(language,'next')}<ArrowRight size={16}/></button>:<button className="primary" onClick={finish}>{tr(language,'finish')}<ArrowRight size={16}/></button>}</div></div></div>
 </motion.div></motion.div></AnimatePresence>
}
