import {useState} from 'react';
import {motion} from 'framer-motion';
import {Leaf,Mail,Lock,ArrowRight,Eye,EyeOff,CloudSun,Sprout,Tractor,CheckCircle2,RefreshCw} from 'lucide-react';
import PixelAuth from '../components/PixelAuth';
import LanguagePicker from '../components/LanguagePicker';
import SiteFooter from '../components/SiteFooter';
import {supabase} from '../lib/supabase';
import {translate as tr} from '../lib/i18n';

export default function Auth({onAuth,language,onLanguage}){
 const [mode,setMode]=useState('signin'),[fullName,setFullName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[verification,setVerification]=useState(false);
 const resetPassword=async()=>{if(!email)return setError('Enter your email first.');setBusy(true);const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/reset`});setBusy(false);if(error)setError(error.message);else setNotice('If an account exists for that email, a password reset link has been sent.')};
 const resend=async()=>{if(!email||!supabase)return;setBusy(true);const {error}=await supabase.auth.resend({type:'signup',email});setBusy(false);if(error)setError(error.message);else setNotice(tr(language,'verificationSent'))};
 const submit=async e=>{e.preventDefault();setError('');setNotice('');if(mode==='signup'&&password!==confirm){setError('Passwords do not match.');return}if(mode==='signup'&&!fullName.trim()){setError(tr(language,'profileNameRequired'));return}setBusy(true);if(!supabase){setNotice('Demo mode: Supabase is not configured. You can continue locally.');setTimeout(()=>onAuth({email:'demo@local'}),500);setBusy(false);return}const result=mode==='signup'?await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${location.origin}/auth/callback`,data:{full_name:fullName.trim()}}}):await supabase.auth.signInWithPassword({email,password});setBusy(false);if(result.error){if(mode==='signin'&&/confirm|verified|verification/i.test(result.error.message)){setVerification(true);return}setError(result.error.message);return}if(mode==='signup'){setVerification(true);return}if(!result.data.user?.email_confirmed_at){setVerification(true);await supabase.auth.signOut();return}onAuth(result.data.user)};
 const signInTab=()=>{setMode('signin');setVerification(false);setError('');setNotice('')};
 return <div className="auth-page"><PixelAuth active={busy}/><div className="auth-landscape"><div className="farm-illustration" aria-label={tr(language,'farmIllustration')}><div className="farm-sky"/><div className="farm-cloud cloud-a"/><div className="farm-cloud cloud-b"/><div className="farm-field field-a"/><div className="farm-field field-b"/><div className="farm-barn"><span className="barn-roof"/><span className="barn-body"/><span className="barn-door"/><span className="barn-window"/></div><div className="crop-row crop-a"/><div className="crop-row crop-b"/><div className="tractor"><Tractor size={42}/></div></div><div className="auth-brand"><div className="brand-mark"><Leaf/></div><div><b>Climate Aware</b><span>AGRICULTURE ASSISTANT</span></div></div><div className="auth-message"><span className="eyebrow"><Sprout size={15}/> {tr(language,'authEyebrow')}</span><h1>{tr(language,'authHero')}<br/><em>{tr(language,'authHeroAccent')}</em></h1><p>{tr(language,'authText')}</p><div className="auth-chip"><CloudSun size={16}/> {tr(language,'farmerLed')}</div></div></div>
 <motion.div className="auth-panel" initial={{opacity:0,y:16}} animate={{opacity:1,y:0}}>
  <div className="auth-panel-head"><div className="mini-brand"><Leaf/> Climate Aware</div><LanguagePicker language={language} onLanguage={onLanguage} compact/></div>
  {verification?<div className="verification-view"><div className="verification-icon"><Mail/></div><span className="eyebrow">EMAIL CONFIRMATION</span><h2>{tr(language,'verificationTitle')}</h2><p>{tr(language,'verificationText')} <b>{email}</b>.</p><div className="verification-note"><CheckCircle2 size={17}/><span>{tr(language,'verificationHint')}</span></div><button className="primary wide" onClick={resend} disabled={busy}><RefreshCw size={16}/>{busy?'Sending…':tr(language,'resendVerification')}</button><button className="secondary wide" onClick={()=>{setVerification(false);setMode('signin');setError('');setNotice('')}}>{tr(language,'changeEmail')}</button><button className="ghost wide" onClick={signInTab}>{tr(language,'backToSignIn')}</button></div>:<>
   <div className="auth-tabs"><button className={mode==='signin'?'active':''} onClick={signInTab}>{tr(language,'signIn')}</button><button className={mode==='signup'?'active':''} onClick={()=>{setMode('signup');setError('');setNotice('')}}>{tr(language,'createAccount')}</button></div>
   <h2>{mode==='signin'?tr(language,'welcomeBack'):tr(language,'startField')}</h2><p className="muted">{mode==='signin'?tr(language,'historyReady'):tr(language,'beginReadings')}</p>
   <form onSubmit={submit}>{mode==='signup'&&<label><span><Leaf size={14}/> {tr(language,'fullName')}</span><input value={fullName} onChange={e=>setFullName(e.target.value)} autoComplete="name" required placeholder={tr(language,'fullNamePlaceholder')}/></label>}<label><span><Mail size={14}/> {tr(language,'email')}</span><input value={email} onChange={e=>setEmail(e.target.value)} type="email" required placeholder="you@example.com"/></label><label><span><Lock size={14}/> {tr(language,'password')}</span><div className="password-wrap"><input value={password} onChange={e=>setPassword(e.target.value)} type={show?'text':'password'} minLength="8" required placeholder="At least 8 characters"/><button type="button" onClick={()=>setShow(v=>!v)} aria-label={show?tr(language,'hidePassword'):tr(language,'showPassword')}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>{mode==='signup'&&<label><span><Lock size={14}/> {tr(language,'confirmPassword')}</span><div className="password-wrap"><input value={confirm} onChange={e=>setConfirm(e.target.value)} type={show?'text':'password'} minLength="8" required placeholder={tr(language,'repeatPassword')}/><button type="button" onClick={()=>setShow(v=>!v)} aria-label={show?tr(language,'hidePassword'):tr(language,'showPassword')}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>}{error&&<div className="error">{error}</div>}{notice&&<div className="notice">{notice}{mode==='signup'&&supabase&&<button type="button" className="inline-link" onClick={resend}>{tr(language,'resendVerification')}</button>}</div>}<button className="primary wide auth-submit" disabled={busy}>{busy?'Preparing your field…':mode==='signin'?tr(language,'enterField'):tr(language,'createField')}<ArrowRight size={18}/></button></form>{mode==='signin'&&<button type="button" className="forgot-link" onClick={resetPassword}>{tr(language,'forgotPassword')}</button>}<div className="auth-footnote">By continuing, you agree to use this as decision support and verify important agricultural decisions locally.</div>
  </>}
 </motion.div><SiteFooter language={language}/></div>
}
