import {useState} from 'react';
import {motion} from 'framer-motion';
import {CloudSun,Droplets,Thermometer,Wind,Sun,Sparkles,ArrowRight,Info,MapPin,Mic2} from 'lucide-react';
import {api} from '../lib/api';
import {translate as tr} from '../lib/i18n';
import VoiceAssistant from '../components/VoiceAssistant';
const initial={farmName:'',location:'',crop:'',cropStage:'Vegetative',acreage:'',temperatureC:'28',humidity:'65',rainfallMm:'4',windKph:'9',soilMoisture:'42',sunlightHours:'7',notes:''};
export default function Home({onReport,language,user}){
 const [f,setF]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(''); const set=(k,v)=>setF(x=>({...x,[k]:v}));
 const applyVoice=(fields,transcript)=>{setF(x=>{const next={...x};for(const [k,v] of Object.entries(fields||{})){if(v!==undefined&&v!==null&&v!=='')next[k]=v}if(fields?.notes)next.notes=fields.notes;return next})};
 const submit=async e=>{e.preventDefault();setError('');setBusy(true);try{const payload={farmName:f.farmName,location:f.location,crop:f.crop,cropStage:f.cropStage,acreage:f.acreage,readings:{temperatureC:f.temperatureC,humidity:f.humidity,rainfallMm:f.rainfallMm,windKph:f.windKph,soilMoisture:f.soilMoisture,sunlightHours:f.sunlightHours,notes:f.notes},language};const r=await api('/api/reports',{method:'POST',body:JSON.stringify(payload)});onReport(r)}catch(e){setError(e.message)}finally{setBusy(false)}};
 const greeting=user?.user_metadata?.full_name||user?.user_metadata?.name||user?.email?.split('@')[0]||'Farmer';
 const metrics=[["temperatureC",'temperature','°C',Thermometer],["humidity",'humidity','%',Droplets],["rainfallMm",'rainfall','mm',CloudSun],["windKph",'wind','km/h',Wind],["soilMoisture",'soil','%',Droplets],["sunlightHours",'sunlight','hours',Sun]];
 return <div className="home"><section className="hero"><div><span className="eyebrow"><Sparkles size={15}/> {tr(language,'heroEyebrow')}</span><div className="greeting">{tr(language,'hello')}, <strong>{greeting}</strong> 🌱</div><h1>{tr(language,'heroTitle')} <em>{tr(language,'heroAccent')}</em></h1><p>{tr(language,'heroText')}</p></div><div className="hero-actions"><div className="hero-badge"><CloudSun/><div><span>{tr(language,'liveContext')}</span><b>{tr(language,'liveContextText')}</b></div></div><VoiceAssistant language={language} onApply={applyVoice}/></div></section>
 <form className="field-form" onSubmit={submit}>
  <motion.section className="input-card form-section" id="field-details" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}><div className="section-head"><div><span className="step">01</span><h2>{tr(language,'fieldDetails')}</h2></div><p>{tr(language,'fieldDetailsHint')}</p></div><div className="grid-3"><label>{tr(language,'farmName')}<input value={f.farmName} onChange={e=>set('farmName',e.target.value)} placeholder="e.g. Green Valley Farm" required/></label><label>{tr(language,'location')}<div className="input-icon"><MapPin size={15}/><input value={f.location} onChange={e=>set('location',e.target.value)} placeholder="Village / district / town"/></div></label><label>{tr(language,'crop')}<input value={f.crop} onChange={e=>set('crop',e.target.value)} placeholder="e.g. Tomato" required/></label><label>{tr(language,'cropStage')}<select value={f.cropStage} onChange={e=>set('cropStage',e.target.value)}>{['Seedling','Vegetative','Flowering','Fruiting','Maturity','Post-harvest'].map(x=><option key={x}>{x}</option>)}</select></label><label>{tr(language,'acreage')}<input type="number" min="0" step="0.1" value={f.acreage} onChange={e=>set('acreage',e.target.value)} placeholder={tr(language,'optional')}/></label></div></motion.section>
  <motion.section className="input-card form-section" id="field-measurements" initial={{opacity:0,y:12}} animate={{opacity:1,y:0,delay:.05}}><div className="section-head"><div><span className="step">02</span><h2>{tr(language,'measurements')}</h2></div><p>{tr(language,'measurementsHint')}</p></div><div className="grid-6">{metrics.map(([k,l,u,I])=><label className="metric" key={k}><span><I size={16}/>{tr(language,l)}</span><div><input type="number" step="0.1" value={f[k]} onChange={e=>set(k,e.target.value)} required/><small>{u}</small></div></label>)}</div></motion.section>
  <motion.section className="input-card form-section" id="field-observations" initial={{opacity:0,y:12}} animate={{opacity:1,y:0,delay:.1}}><div className="section-head"><div><span className="step">03</span><h2>{tr(language,'observations')}</h2></div><p>{tr(language,'observationsHint')}</p></div><textarea value={f.notes} onChange={e=>set('notes',e.target.value)} placeholder={tr(language,'notesHint')}/><div className="optional-note"><Info size={15}/><span>{tr(language,'demoNote')}</span></div></motion.section>
  <motion.section className="input-card form-section action-card" id="field-report" initial={{opacity:0,y:12}} animate={{opacity:1,y:0,delay:.15}}><div className="report-action-copy"><span className="eyebrow"><Sparkles size={14}/> AI CLIMATE REPORT</span><h2>{tr(language,'reportAction')}</h2><p>{tr(language,'heroText')}</p></div>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?tr(language,'generating'):tr(language,'generate')}<ArrowRight size={18}/></button></motion.section>
 </form>
 </div>
}
